import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AnimationProvider, Header, Footer } from "@/components";
import NavContextProvider from "@/components/NavContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <AnimationProvider>
          <NavContextProvider>
            <Header />
          </NavContextProvider>
          {children}
          <Footer />
        </AnimationProvider>
      </body>
    </html>
  );
}
