import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AnimationProvider } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <AnimationProvider>
          <header className="flex justify-between items-center px-2 sticky top-0 bg-white z-10 border">
            <h1 className="text-2xl">Menu</h1>
            <div className="flex gap-2 text-sm">
              <p>Make your reservation:</p>
              <p className="font-semibold">(415)&nbsp;555&#8209;0132</p>
            </div>
          </header>
          {children}
        </AnimationProvider>
      </body>
    </html>
  );
}
