import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AnimationProvider } from "@/components";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark scroll-smooth focus:scroll-auto">
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <AnimationProvider>
          <Header />
          {children}
          <footer className="bg-green-700 px-2 py-10 text-white">
            @digitmonkey
          </footer>
        </AnimationProvider>
      </body>
    </html>
  );
}
